# Site settings
title: ANTH 205
tagline: Biological Anthroplogy
email: 
description: This website is a repository for content and other teaching materials for ANTH 205 (Biological Anthropology) at Lower Columbia College.
baseurl: "/Anth205" # the subpath of your site, e.g. /blog/
url: "http://bateyt.github.io" # the base hostname & protocol for your site
twitter_username: bateytk
github_username:  bateyt

# Build settings
markdown: kramdown
